CREATE OR REPLACE TABLE CDO_FINANCE.IFM.PROVIDERMARGIN_PRIMEWEST(		
	PROVIDER_ID		VARCHAR COLLATE 'LOWER',
	CLOSE_MONTH		DATE NOT NULL,
	COVERAGE_MONTH		DATE NOT NULL,
	Insurance_Company		VARCHAR COLLATE 'LOWER',
	Facility_Name		VARCHAR COLLATE 'LOWER',
	PCP_ID		VARCHAR COLLATE 'LOWER',
	DESCRIPTION		VARCHAR COLLATE 'LOWER',
	AMOUNT		NUMBER(38,4),
	COMPANY		VARCHAR COLLATE 'LOWER',
	PRODUCT		VARCHAR COLLATE 'LOWER',
	TAXONOMY		VARCHAR COLLATE 'LOWER',
	GROUPER_ID		VARCHAR COLLATE 'LOWER',
	LOADDATE		TIMESTAMP_NTZ(9) NOT NULL
	);
