SELECT  'SELECT ' + '''' + table_schema + '''' + ' AS SCHEMA_NAME,' + ''''  + table_name + '''' + ' AS TABLE_NAME,' +

'''' + column_name + '''' + ' AS COLUMN_NAME,MAX(LEN([' + COLUMN_NAME + '])) AS MAXLEN ' +

'FROM ' + table_schema + '.' + table_name + ' UNION ALL'

from information_schema.COLUMNS

where data_type in ('char','nvarchar','varchar','text')

And table_name = 'IFM_ServiceFund_Aetna_CCS' ;

 

 

with cte(schemaname,TABLE_NAME,COLUMN_NAME,MAXLEN) as

(

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'InsuranceCompany' AS COLUMN_NAME,MAX(LEN([InsuranceCompany])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'OfficeName' AS COLUMN_NAME,MAX(LEN([OfficeName])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'SFPCPName' AS COLUMN_NAME,MAX(LEN([SFPCPName])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'PCPLastName' AS COLUMN_NAME,MAX(LEN([PCPLastName])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'PCPFirstName' AS COLUMN_NAME,MAX(LEN([PCPFirstName])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'PCPID' AS COLUMN_NAME,MAX(LEN([PCPID])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'MemberID' AS COLUMN_NAME,MAX(LEN([MemberID])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'MCARE_ID' AS COLUMN_NAME,MAX(LEN([MCARE_ID])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'MemberName' AS COLUMN_NAME,MAX(LEN([MemberName])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'SFGender' AS COLUMN_NAME,MAX(LEN([SFGender])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Hospice' AS COLUMN_NAME,MAX(LEN([Hospice])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'ESRD' AS COLUMN_NAME,MAX(LEN([ESRD])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Institutional' AS COLUMN_NAME,MAX(LEN([Institutional])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'NursingHomeCertifiable' AS COLUMN_NAME,MAX(LEN([NursingHomeCertifiable])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'PreviouslyDisabled' AS COLUMN_NAME,MAX(LEN([PreviouslyDisabled])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'CurrentMember' AS COLUMN_NAME,MAX(LEN([CurrentMember])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Level' AS COLUMN_NAME,MAX(LEN([Level])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'LOB' AS COLUMN_NAME,MAX(LEN([LOB])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'PlanCode' AS COLUMN_NAME,MAX(LEN([PlanCode])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'PlanName' AS COLUMN_NAME,MAX(LEN([PlanName])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'IPAName' AS COLUMN_NAME,MAX(LEN([IPAName])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'PBP' AS COLUMN_NAME,MAX(LEN([PBP])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'ProductType' AS COLUMN_NAME,MAX(LEN([ProductType])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Product' AS COLUMN_NAME,MAX(LEN([Product])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Contract' AS COLUMN_NAME,MAX(LEN([Contract])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Company' AS COLUMN_NAME,MAX(LEN([Company])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'ZeroPrem' AS COLUMN_NAME,MAX(LEN([ZeroPrem])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Market' AS COLUMN_NAME,MAX(LEN([Market])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Cohort' AS COLUMN_NAME,MAX(LEN([Cohort])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Region' AS COLUMN_NAME,MAX(LEN([Region])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS UNION ALL

SELECT 'STG' AS SCHEMA_NAME,'IFM_ServiceFund_Aetna_CCS' AS TABLE_NAME,'Org' AS COLUMN_NAME,MAX(LEN([Org])) AS MAXLEN FROM STG.IFM_ServiceFund_Aetna_CCS

),

cte_1(Table_Name,SchemaName,COLUMN_NAME,Data_Type,MAX_LENGTH) as

(

SELECT t.name AS TableName,

    SCHEMA_NAME(t.schema_id) AS SchemaName,

    c.name as COLUMN_NAME,

                tp.name as DataType,

                c.max_length as MAX_LENGTH

FROM sys.tables AS t

    INNER JOIN sys.columns c ON t.OBJECT_ID = c.OBJECT_ID

    INNER JOIN sys.types tp ON c.system_type_id =  tp.system_type_id

                WHERE SCHEMA_NAME(t.schema_id)='stg'        

                and  t.name='IFM_ServiceFund_Aetna_CCS'

)

select A.TABLE_NAME,A.COLUMN_NAME,B.Data_Type,A.maxlen as oldlength,CASE WHEN A.MAXLEN BETWEEN 0 and 10 THEN 25

WHEN A.MAXLEN BETWEEN 11 and 40 THEN 50

WHEN A.MAXLEN BETWEEN 41 and 85 THEN 100

WHEN A.MAXLEN BETWEEN 86 and 150 THEN 200

WHEN A.MAXLEN BETWEEN 151 and 220 THEN 255

WHEN A.MAXLEN BETWEEN 221 and 275 THEN 300

WHEN A.MAXLEN BETWEEN 276 and 450 THEN 500

WHEN A.MAXLEN IS NULL THEN B.MAX_LENGTH

ELSE 16777216

END AS NEW_UNIFORM_LEN

from cte A LEFT JOIN cte_1 B on A.Table_Name=B.Table_Name and A.COLUMN_NAME=B.COLUMN_NAME

order by A.COLUMN_NAME