USE [TranscendAnalytics]
GO

/****** Object:  Table [STG].[IFM_ServiceFund_Aetna_CCS]    Script Date: 8/5/2024 3:47:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [STG].[IFM_ServiceFund_Aetna_CCS](
	[ID_column] [int] IDENTITY(1,1) NOT NULL,
	[InsuranceCompany] [varchar](50) NULL,
	[InsuranceCompanyID] [int] NULL,
	[OfficeName] [varchar](100) NULL,
	[SFPCPName] [varchar](102) NULL,
	[PCPLastName] [varchar](50) NULL,
	[PCPFirstName] [varchar](50) NULL,
	[PCPID] [varchar](50) NULL,
	[MemberID] [varchar](15) NOT NULL,
	[MCARE_ID] [varchar](15) NULL,
	[Cov_Month] [date] NOT NULL,
	[Close_Month] [date] NOT NULL,
	[RiskScoreC] [decimal](6, 4) NULL,
	[RiskScore_Recon] [decimal](6, 4) NULL,
	[CMSFundingA] [decimal](15, 4) NULL,
	[CMSFundingB] [decimal](15, 4) NULL,
	[CMSFundingC] [decimal](15, 4) NULL,
	[CMSFundingD] [decimal](15, 4) NULL,
	[CMSTotalFunding] [decimal](15, 4) NULL,
	[ProviderFundingA] [decimal](15, 4) NULL,
	[ProviderFundingB] [decimal](15, 4) NULL,
	[ProviderFundingC] [decimal](15, 4) NULL,
	[ProviderFundingD] [decimal](15, 4) NULL,
	[PartDReserve] [decimal](15, 4) NULL,
	[ProviderTotalFunding] [decimal](15, 4) NULL,
	[SpecCap] [decimal](15, 4) NULL,
	[PCPCap] [decimal](15, 4) NULL,
	[ClaimsPartA] [decimal](15, 4) NULL,
	[ClaimsPartA_IP] [decimal](15, 4) NULL,
	[ClaimsPartA_OP] [decimal](15, 4) NULL,
	[ClaimsPartA_Other] [decimal](15, 4) NULL,
	[ClaimsPartB] [decimal](15, 4) NULL,
	[ProfClaims] [decimal](15, 4) NULL,
	[RX_B_Claims] [decimal](15, 4) NULL,
	[RX_D_Claims] [decimal](15, 4) NULL,
	[RX_Rebates] [decimal](15, 4) NULL,
	[RX_Stoploss] [decimal](15, 4) NULL,
	[RX_LICS] [decimal](15, 4) NULL,
	[RX_Quality] [decimal](15, 4) NULL,
	[RX_GDCA] [decimal](15, 4) NULL,
	[RX_REP_GAP_DSCNT] [decimal](15, 4) NULL,
	[RX_RISK_CORRIDOR] [decimal](15, 4) NULL,
	[RX_D__EXP] [decimal](15, 4) NULL,
	[TotalClaims] [decimal](15, 4) NULL,
	[StopLossFee] [decimal](15, 4) NULL,
	[ReinRecoveries] [decimal](15, 4) NULL,
	[Adjustment] [decimal](15, 4) NULL,
	[FactorMonth] [int] NULL,
	[IBNRPartA] [decimal](15, 4) NULL,
	[IBNRPartB] [decimal](15, 4) NULL,
	[IBNR] [decimal](15, 4) NULL,
	[Tot_Exp] [decimal](22, 4) NULL,
	[Net] [decimal](24, 4) NULL,
	[MemberName] [varchar](100) NULL,
	[SFBirthDate] [datetime] NULL,
	[SFGender] [varchar](1) NULL,
	[Hospice] [varchar](1) NULL,
	[ESRD] [varchar](1) NULL,
	[Institutional] [varchar](1) NULL,
	[NursingHomeCertifiable] [varchar](3) NULL,
	[PreviouslyDisabled] [varchar](1) NULL,
	[CurrentMember] [varchar](10) NULL,
	[Level] [varchar](10) NULL,
	[LOB] [varchar](16) NULL,
	[PlanCode] [varchar](16) NULL,
	[PlanName] [varchar](50) NULL,
	[IPAName] [varchar](100) NULL,
	[PBP] [nvarchar](3) NULL,
	[Age] [decimal](5, 1) NULL,
	[ProductType] [varchar](50) NULL,
	[Product] [varchar](10) NULL,
	[Contract] [varchar](15) NULL,
	[Company] [varchar](50) NULL,
	[ZeroPrem] [varchar](3) NULL,
	[LoadDate] [date] NULL,
	[Market] [varchar](50) NULL,
	[Cohort] [varchar](100) NULL,
	[Region] [varchar](100) NULL,
	[Org] [varchar](100) NULL
) ON [PRIMARY]
GO

